ITEM.name = "Welder"
ITEM.desc = "A welder"
ITEM.model = "models/warz/melee/powerdrill.mdl"
ITEM.class = "hl2_m_taladro"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 0
ITEM.category = "Tool"
ITEM.cant = 1
