ENT.Base = "nut_readerbase"
ENT.Type = "anim"
ENT.PrintName = "Level 0 MCR"
ENT.Author = "La Corporativa"
ENT.Spawnable = true
ENT.AdminOnly = true
ENT.Category = "NutScript"
ENT.Level = "Level 0"
ENT.Cards = {"nuckey"}
