ENT.Base = "nut_readerbase"
ENT.Type = "anim"
ENT.PrintName = "Level 3 MCR"
ENT.Author = "La Corporativa"
ENT.Spawnable = true
ENT.AdminOnly = true
ENT.Category = "NutScript"
ENT.Level = "Level 3"
ENT.Cards = {"utckey", "comkey", "admkey", "nuckey"}
