ITEM.name = "Broom"
ITEM.base = "base_wep"
ITEM.uniqueID = "weapon_broom"
ITEM.category = "Utils"
ITEM.class = "weapon_broom"
ITEM.type = "melee"
ITEM.flag = "i"
ITEM.model = Model("models/props_c17/escoba.mdl")
ITEM.desc = "A broom."
ITEM.price = 270
ITEM.weight = 1